# Generated by Django 5.1.3 on 2024-12-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('tech', 'Technology'), ('health', 'Health'), ('sports', 'Sports'), ('education', 'Education'), ('news', 'News')], default='tech', max_length=50),
        ),
    ]
